// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystem.Entities2
{
    [Table("Course")]
    [Index(nameof(CrsName), Name = "CrsName", IsUnique = true)]
    public partial class Course
    {
        public Course()
        {
            Exams = new HashSet<Exam>();
            Depts = new HashSet<Department>();
            Ins = new HashSet<Instructor>();
            Topics = new HashSet<Topic>();
        }

        [Key]
        [Column("Crs_ID")]
        public int CrsId { get; set; }
        [Column("Crs_Name")]
        [StringLength(50)]
        [Unicode(false)]
        public string CrsName { get; set; }
        [Column("Crs_Duration")]
        public TimeSpan? CrsDuration { get; set; }

        [InverseProperty(nameof(Exam.Crs))]
        public virtual ICollection<Exam> Exams { get; set; }

        [ForeignKey("CrsId")]
        [InverseProperty(nameof(Department.Crs))]
        public virtual ICollection<Department> Depts { get; set; }
        [ForeignKey("CrsId")]
        [InverseProperty(nameof(Instructor.Crs))]
        public virtual ICollection<Instructor> Ins { get; set; }
        [ForeignKey("CrsId")]
        [InverseProperty(nameof(Topic.Crs))]
        public virtual ICollection<Topic> Topics { get; set; }
    }
}