// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystem.Entities2
{
    [Table("Department")]
    public partial class Department
    {
        public Department()
        {
            Instructors = new HashSet<Instructor>();
            Students = new HashSet<Student>();
            Crs = new HashSet<Course>();
            Ins = new HashSet<Instructor>();
        }

        [Key]
        [Column("Dept_ID")]
        public int DeptId { get; set; }
        [Required]
        [Column("Dept_Name")]
        [StringLength(50)]
        [Unicode(false)]
        public string DeptName { get; set; }
        [Column("Dept_Location")]
        [StringLength(50)]
        [Unicode(false)]
        public string DeptLocation { get; set; }
        [Column("Dept_Manager")]
        public int? DeptManager { get; set; }
        [Column("Manager_Hiredate", TypeName = "date")]
        public DateTime? ManagerHiredate { get; set; }

        [ForeignKey(nameof(DeptManager))]
        [InverseProperty(nameof(Instructor.Departments))]
        public virtual Instructor DeptManagerNavigation { get; set; }
        [InverseProperty(nameof(Instructor.Dept))]
        public virtual ICollection<Instructor> Instructors { get; set; }
        [InverseProperty(nameof(Student.Dept))]
        public virtual ICollection<Student> Students { get; set; }

        [ForeignKey("DeptId")]
        [InverseProperty(nameof(Course.Depts))]
        public virtual ICollection<Course> Crs { get; set; }
        [ForeignKey("DeptId")]
        [InverseProperty(nameof(Instructor.Depts))]
        public virtual ICollection<Instructor> Ins { get; set; }
    }
}