// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystem.Entities2
{
    [Table("Exam")]
    public partial class Exam
    {
        public Exam()
        {
            ExamQuestions = new HashSet<ExamQuestion>();
            StudExams = new HashSet<StudExam>();
        }

        [Key]
        [Column("Exam_ID")]
        public int ExamId { get; set; }
        [Column("Exam_Date", TypeName = "date")]
        public DateTime ExamDate { get; set; }
        [Column("Exam_Duration")]
        public TimeSpan? ExamDuration { get; set; }
        [Column("Crs_ID")]
        public int? CrsId { get; set; }

        [ForeignKey(nameof(CrsId))]
        [InverseProperty(nameof(Course.Exams))]
        public virtual Course Crs { get; set; }
        [InverseProperty(nameof(ExamQuestion.Exam))]
        public virtual ICollection<ExamQuestion> ExamQuestions { get; set; }
        [InverseProperty(nameof(StudExam.Exam))]
        public virtual ICollection<StudExam> StudExams { get; set; }
    }
}