// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystem.Entities2
{
    [Table("Exam_Questions")]
    public partial class ExamQuestion
    {
        [Key]
        [Column("Exam_ID")]
        public int ExamId { get; set; }
        [Key]
        [Column("Q_ID")]
        public int QId { get; set; }
        [Column("Question_No")]
        public int? QuestionNo { get; set; }

        [ForeignKey(nameof(ExamId))]
        [InverseProperty("ExamQuestions")]
        public virtual Exam Exam { get; set; }
        [ForeignKey(nameof(QId))]
        [InverseProperty(nameof(Question.ExamQuestions))]
        public virtual Question QIdNavigation { get; set; }
    }
}