// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystem.Entities2
{
    [Table("Instructor")]
    public partial class Instructor
    {
        public Instructor()
        {
            Departments = new HashSet<Department>();
            Crs = new HashSet<Course>();
            Depts = new HashSet<Department>();
        }

        [Key]
        [Column("Ins_ID")]
        public int InsId { get; set; }
        [Required]
        [Column("Ins_Name")]
        [StringLength(50)]
        [Unicode(false)]
        public string InsName { get; set; }
        [Column("Ins_Degree")]
        [StringLength(50)]
        [Unicode(false)]
        public string InsDegree { get; set; }
        [Column("salary")]
        public int? Salary { get; set; }
        [Column("Dept_ID")]
        public int? DeptId { get; set; }

        [ForeignKey(nameof(DeptId))]
        [InverseProperty(nameof(Department.Instructors))]
        public virtual Department Dept { get; set; }
        [InverseProperty(nameof(Department.DeptManagerNavigation))]
        public virtual ICollection<Department> Departments { get; set; }

        [ForeignKey("InsId")]
        [InverseProperty(nameof(Course.Ins))]
        public virtual ICollection<Course> Crs { get; set; }
        [ForeignKey("InsId")]
        [InverseProperty(nameof(Department.Ins))]
        public virtual ICollection<Department> Depts { get; set; }
    }
}