// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystem.Entities2
{
    [Table("Question")]
    public partial class Question
    {
        public Question()
        {
            ExamQuestions = new HashSet<ExamQuestion>();
        }

        [Key]
        [Column("Q_ID")]
        public int QId { get; set; }
        [Required]
        [Column("Q_Question")]
        [StringLength(800)]
        [Unicode(false)]
        public string QQuestion { get; set; }
        [Column("Q_Type")]
        [StringLength(20)]
        [Unicode(false)]
        public string QType { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string Option1 { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string Option2 { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string Option3 { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string Option4 { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string CourseName { get; set; }
        [Column("Model_Answer")]
        [StringLength(100)]
        [Unicode(false)]
        public string ModelAnswer { get; set; }

        [InverseProperty(nameof(ExamQuestion.QIdNavigation))]
        public virtual ICollection<ExamQuestion> ExamQuestions { get; set; }
    }
}