// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystem.Entities2
{
    [Table("Stud_Exam")]
    public partial class StudExam
    {
        [Key]
        [Column("St_ID")]
        public int StId { get; set; }
        [Key]
        [Column("Exam_ID")]
        public int ExamId { get; set; }
        [Column("Answer_Q1")]
        [StringLength(100)]
        public string AnswerQ1 { get; set; }
        [Column("Answer_Q2")]
        [StringLength(100)]
        public string AnswerQ2 { get; set; }
        [Column("Answer_Q3")]
        [StringLength(100)]
        public string AnswerQ3 { get; set; }
        [Column("Answer_Q4")]
        [StringLength(100)]
        public string AnswerQ4 { get; set; }
        [Column("Answer_Q5")]
        [StringLength(100)]
        public string AnswerQ5 { get; set; }
        [Column("Answer_Q6")]
        [StringLength(100)]
        public string AnswerQ6 { get; set; }
        [Column("Answer_Q7")]
        [StringLength(100)]
        public string AnswerQ7 { get; set; }
        [Column("Answer_Q8")]
        [StringLength(100)]
        public string AnswerQ8 { get; set; }
        [Column("Answer_Q9")]
        [StringLength(100)]
        public string AnswerQ9 { get; set; }
        [Column("Answer_Q10")]
        [StringLength(100)]
        public string AnswerQ10 { get; set; }
        public int Grade { get; set; }

        [ForeignKey(nameof(ExamId))]
        [InverseProperty("StudExams")]
        public virtual Exam Exam { get; set; }
        [ForeignKey(nameof(StId))]
        [InverseProperty(nameof(Student.StudExams))]
        public virtual Student St { get; set; }
    }
}