// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystem.Entities2
{
    [Table("Topic")]
    public partial class Topic
    {
        public Topic()
        {
            Crs = new HashSet<Course>();
        }

        [Key]
        [Column("Topic_ID")]
        public int TopicId { get; set; }
        [Required]
        [Column("Topic_Name")]
        [StringLength(50)]
        [Unicode(false)]
        public string TopicName { get; set; }

        [ForeignKey("TopicId")]
        [InverseProperty(nameof(Course.Topics))]
        public virtual ICollection<Course> Crs { get; set; }
    }
}